# Generated by Django 6.0.4 on 2026-04-25 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('edr', '0002_treatment_status_treatment_treatment_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Dental Invoice',
                'verbose_name_plural': 'Dental Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.invoice',),
        ),
        migrations.CreateModel(
            name='PharmacyInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Pharmacy Invoice',
                'verbose_name_plural': 'Pharmacy Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.invoice',),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('dental', 'Dental'), ('pharmacy', 'Pharmacy')], default='dental', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='edr.treatment'),
        ),
    ]
