# Generated by Django 6.0.4 on 2026-04-26 00:00
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_role', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='accounts.user')),
            ],
        ),
    ]
