# Generated by Django 6.0.4 on 2026-04-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='created_on',
        ),
    ]
