# Generated by Django 6.0.4 on 2026-04-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
